#src/models/state.py
from typing import List, Optional, Annotated, TypedDict, Any
from uuid import UUID, uuid4
from pydantic import BaseModel, Field
from langchain_core.messages import BaseMessage
import operator

# ==========================================
# 1. API Ingress & Egress Models
# ==========================================

class TaskRequest(BaseModel):
    """Incoming request payload from the API Gateway."""
    prompt: str = Field(..., min_length=10, description="The user's task or goal to be executed.")
    user_id: str = Field(..., description="Identifier for the requesting user.")
    idempotency_key: UUID = Field(
        default_factory=uuid4,
        description="UUID v4 to guarantee task idempotency across retries."
    )
    context: Optional[dict[str, Any]] = Field(default=None, description="Optional metadata for the task.")

class TaskResponse(BaseModel):
    """Immediate response returned to the user (Fire-and-Forget)."""
    task_id: UUID
    status: str = "accepted"
    message: str = "Task queued for orchestration."

# ==========================================
# 2. Agent Structured Outputs (The Gate)
# ==========================================

class AgentResponse(BaseModel):
    """
    Standardized output required from every Agent node.
    Enforces the DEVDOC.md confidence score constraint.
    """
    analysis: str = Field(..., description="The step-by-step reasoning for the decision.")
    tool_to_call: Optional[str] = Field(None, description="The exact name of the MCP tool to execute, if any.")
    tool_arguments: Optional[dict[str, Any]] = Field(None, description="JSON arguments for the requested tool.")
    confidence_score: float = Field(
        ...,
        ge=0.7,
        le=1.0,
        description="Agent's confidence in this action. Must be >= 0.7."
    )
    is_complete: bool = Field(default=False, description="True if the overall task is successfully resolved.")

# ==========================================
# 3. LangGraph Workflow State
# ==========================================

class AgentState(TypedDict):
    """
    The state dictionary passed between nodes in the LangGraph workflow.
    We use Annotated with operator.add for messages so they append rather than overwrite.
    """
    messages: Annotated[List[BaseMessage], operator.add]
    task_id: UUID
    idempotency_key: UUID
    current_agent: str
    next_node: Optional[str]         # This dedicated routing field
    plan: List[str]                  # Steps laid out by the Supervisor
    completed_steps: List[str]       # Steps successfully executed
    final_report: Optional[str]      # The synthesis generated by the Finalizer
    error_count: int                 # Track failures for the Self-Correction loop